### ISSUE TITLE
[QoL] Send uncompressed video files

### ISSUE THREAD

**Issue by SadmL** [kukuruzka165/materialgram#22]
### Is your feature request related to a problem?

Sometimes I need to send some video files uncompressed. For now I transfer files to smartphone and send them from it in uncompressed state. 

### Describe the solution you'd like

"Compress" checkbox on file send.

### Describe alternatives you've considered

x

### Additional context

Flatpak v. 5.0.0.1
Idk is this feature exits in windows version or not, but may be I'm blind and couldn't find it at first glance.

**Comment by kukuruzka165** [comment]
![materialgram_54n5DGEuEs](https://github.com/kukuruzka165/materialgram/assets/60149954/3563c1df-5eef-437a-9cf8-58195bbbe652)
no way you don't have this

**Comment by SadmL** [comment]
I'm dumb 🙃
I'll edit title
I mean only videos, Idk why I also write pictures...

**Comment by kukuruzka165** [comment]
unlike mobile clients, telegram desktop does not compress videos as far as i know

**Comment by SadmL** [comment]
Yep, just download TD and there is no compress checkbox. Well, shiet. 
Close then as not planned?
