### ISSUE TITLE
ADD A FUCKING WINDOWS INSTALLER

### ISSUE THREAD

**Issue by kernel86-64** [kukuruzka165/materialgram#32]
### Is your feature request related to a problem?

ADD A FUCKING WINDOWS INSTALLER

### Describe the solution you'd like

ADD A FUCKING WINDOWS INSTALLER

### Describe alternatives you've considered

ADD A FUCKING WINDOWS INSTALLER

**Comment by ghazzor** [comment]
why do you need it tho , just place the executable in some folder and you are done

**Comment by xienuss** [comment]
blud for real needs this windows installer :sob:

**Comment by VladP812** [comment]
GIVE HIM DAT .MSI RIGHT NOW 😡

**Comment by JDJGInc** [comment]
> ### Is your feature request related to a problem?
> ADD A FUCKING WINDOWS INSTALLER
> 
> ### Describe the solution you'd like
> ADD A FUCKING WINDOWS INSTALLER
> 
> ### Describe alternatives you've considered
> ADD A FUCKING WINDOWS INSTALLER
> 
> ### Additional context
> _No response_

What makes you need a windows installer?
is there some aspect you believe requires one?

@kernel86-64 if you need tech help you are welcome to contact me on discord with jdjg.
I can help you but most of the time you don't need a windows installer.

**Comment by incycledream** [comment]
Shut the fuck up please, I'll make a Windows installer
