### ISSUE TITLE
Dark/night mode text selection unclear

### ISSUE THREAD

**Issue by mortn** [kukuruzka165/materialgram#9]
### Steps to reproduce

1. Enable dark mode
2. Select text in message

### Expected behaviour

Text selected should be clearly distinguishable from regular text

### Actual behaviour

In dark mode, when selecting text the selection is almost invisible with just a minimal color difference. 

### Operating system

Debian 12 (Gnome)

### Version of Telegram Desktop

4.14.9.1

### Installation source

Static binary from official website

**Comment by kukuruzka165** [comment]
i made the selection color darker in 4.14.13.1, check it out
or is it better to replace it with an accent color? it just might break readability of the text if people just put white instead of accent color
